services:
  - type: web
    name: fraud-detection-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app.routes:app"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://your-mongo-db-url
